default:
  image: alpine:latest
  tags:
    - AMD64

stages:
  - lint
  - deploy

linter:
  stage: lint
  image: node:latest
  allow_failure: true
  script:
    - npm install -g prettier sass-lint
    - prettier templates/ -w
    - sass-lint static/sass/*.sass
    - git add .
    - git config --global user.email "contact@ilearned.eu"
    - git config --global user.name "Gitlab CI"
    - git commit -m "[🧹 Lint] Linted code"
    - git push https://CI_CD:$CI_GIT_USER_PASSWD@gitlab.ilearned.eu/i-learned/website/ HEAD:main

  only:
    - main

prod-deploy-job:
  stage: deploy
  image: hub.ilearned.eu/i-learned/ci-cd/website-builder
  script:
    - python3 build.py
    - wget https://github.com/tdewolff/minify/releases/download/v2.10.0/minify_linux_amd64.tar.gz
    - tar -xf minify_linux_amd64.tar.gz -C /tmp
    - bash /tmp/minify --html-keep-comments -r -o output/ output/
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - rsync -az --exclude=".git*" --delete -e "ssh -p 53453 -i ~/.ssh/id_ed25519" output/ ci@web.ramle.be:/var/www/beta.ilearned.eu

  only:
    - main

  artifacts:
    paths:
      - output
