default:
  image: alpine:latest
  tags:
    - AMD64

stages:
  - lint
  - pages

linter:
  stage: lint
  image: node:latest
  allow_failure: true
  script:
    - npm install -g prettier sass-lint
    - prettier templates/ -w
    - sass-lint static/sass/*.sass
    - git add .
    - git config --global user.email "contact@ilearned.eu"
    - git config --global user.name "Gitlab CI"
    - git commit -m "[🧹 Lint] Linted code"
    - git push https://CI_CD:$CI_GIT_USER_PASSWD@gitlab.ilearned.eu/i-learned/website/ HEAD:main

  only:
    - main

pages:
  stage: pages
  script:
    - apk add gcc python3-dev linux-headers musl-dev g++ py3-pip
    - pip3 install -r requirements.txt
    - python3 build.py
  artifacts:
    paths:
      - output
